### ISSUE TITLE
Help needed related to parameter count

### ISSUE THREAD

**Issue by manusheoran** [ksouvik52/Pre-defined-sparseCNN#1]
@ksouvik52, Hey!!! can you help me with the parameter count. 
I tried to run the following codes,
https://github.com/ksouvik52/Pre-defined-sparseCNN/blob/f41b11c1c743437d8e0ade72662ec365dac2da3f/VGG16_pSC2_periodic/VGG16_pSC2_with3x3_P8_cifar10_wrapper.py#L121

https://github.com/ksouvik52/Pre-defined-sparseCNN/blob/f41b11c1c743437d8e0ade72662ec365dac2da3f/VGG16_pSC4_periodic/VGG16_pSC4_with3x3_P16_cifar10_wrapper.py#L121

According to the paper, parameter count should be different for both codes, but the output for both codes is same, i.e. "Total trainable parameters:  14728266". 
Is there anything that I'm missing? Or there is another way to count parameters?

**Comment by ksouvik52** [comment]
Hi, you need to multiply that value with the density factor, which is (4/9) for pSC4 and (2/9) for pSC2 for the CONVs. Then you will roughly get the values as mentioned in the paper. For the models with periodically repeating dense kernels at a period of 8 with pSC2, the density factor is = [(2/9)*7 + 9]/72 = 23/72. I hope, it clears your confusion. Let me know if there is any doubt.
